# CharForge runtime stub — char_kade
# Entity type: character
# Auto-generated by Spatha Promotion Pass capsule build — 2026-07-21T00:00:00Z

def on_turn_start(state, context):
    return state

def on_turn_end(state, context):
    return state

def on_event(state, event, context):
    return state
