# CharForge runtime stub — char_darek_voss
# Entity type: character
# TERMINAL STATE: subject deceased (KIA). Historical record; not for live instantiation.
# Auto-generated by Sentinel Team Capsule Build — 2026-07-21

def on_turn_start(state, context):
    return state

def on_turn_end(state, context):
    return state

def on_event(state, event, context):
    return state
