# CharForge runtime stub — malrik_voska
# Entity type: character
# Auto-generated by full_promotion_pass.py — 2026-03-20T02:03:35Z

def on_turn_start(state, context):
    return state

def on_turn_end(state, context):
    return state

def on_event(state, event, context):
    return state
