# CharForge runtime stub — char_aric_thal
# Entity type: character
# Auto-generated by Sentinel Team Capsule Build — 2026-07-21

def on_turn_start(state, context):
    return state

def on_turn_end(state, context):
    return state

def on_event(state, event, context):
    return state
